---
#- debug: msg="{{ lookup('template', 'auth_body.json') }}"

- name: Authenticate
  uri: 
    url: '{{ restpoint_url }}/authenticate/'
    method: POST
    body_format: json
    body: "{{ lookup('template', 'auth_body.json') }}"
    headers:
       Content-type: "application/oracle-compute-v3+json"
    validate_certs: no
    status_code: 204
  register: auth_cookie

- name: Get Orchestrations
  uri:
    url: "{{ restpoint_url }}/orchestration/Compute-{{ id_domain }}/"
    method: GET
    headers:
       Accept: "application/oracle-compute-v3+json"
       Cookie: "{{ auth_cookie.set_cookie }}"

- name: Create Orchestration
  uri:
    url: "{{ restpoint_url }}/orchestration/Compute-{{ id_domain }}/"
    method: POST
    validate_certs: no
    headers:
       Content-type: "application/oracle-compute-v3+json"
       Accept: "application/oracle-compute-v3+json"
       Cookie: "{{ auth_cookie.set_cookie }}"
    body: "{{ lookup('template', 'orch.json') }}"
    return_content: yes
  register: orchestration_creation_details

- name: Start Orchestration
  uri:
    url: "{{ restpoint_url }}/orchestration/Compute-{{ id_domain }}/{{ orch_name }}?action=START"
    method: PUT
    validate_certs: no
    headers:
       Content-type: "application/oracle-compute-v3+json"
       Accept: "application/oracle-compute-v3+json"
       Cookie: "{{ auth_cookie.set_cookie }}"
    return_content: yes
  register: orchestration_start_details

